name: Rust Dev Builds

on:
  push:
    branches: [ '!master' ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libfltk-gl1.3 xorg-dev libpango1.0-dev librust-pangocairo-dev libpangoxft-1.0 libwayland-dev libxkbcommon-dev libdbus-1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: scrappy-linux
        path: target/release/scrappy

  windows:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: scrappy-windows.exe
          path: target/release/scrappy.exe
