name: Rust Release Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libfltk-gl1.3 xorg-dev libpango1.0-dev librust-pangocairo-dev libpangoxft-1.0
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: scrappy-linux
        path: target/release/scrappy

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: scrappy-windows.exe
          path: target/release/scrappy.exe
  
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs:
      - windows
      - linux
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          path: .binaries/
      - name: Do Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 17.1.1
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          extra_plugins: |
            @google/semantic-release-replace-plugin
            @semantic-release/git
            conventional-changelog-ember
