name: Rust Package Updates

on:
  schedule:
    - cron: "0 7 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Cargo Update
        id: update
        run: cargo update
      - name: Dev Build - Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfltk1.3-dev libfltk-gl1.3 xorg-dev
      - name: Dev Build - Build
        run: cargo build --verbose
      - name: Dev Build - Run tests
        run: cargo test --verbose
      - name: Commit Cargo.lock if build succeeds
        if: ${{ success() }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[bugfix packages] Automatic package updates"
          file_pattern: Cargo.lock
      - name: Create a broken PR if build failed
        if: ${{ failure() }}
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "[minor packages] Automatic package updates - build failed"
          title: "Package update failed"
          labels: bug

